export const colors = {
  overcastSky: '#dfe3e6',
  darkSky: '#324c5c',
  boneWhite: '#cccfbe',
  lavender: '#c0b1c9',
  celadon: '#B2EBBB',
  middleBlue: '#8BCCD0',
  maximumBlue: '#5EA3B6',
  shadowBlue: '#798EA9',
  blueBell: '#918BC7',
  kobi: '#CC97B1',
  apricot: '#FDC7AA',
  transparent: 'rgba(0, 0, 0, 0)',
  melon: '#FFC3B5',
  mindaro: '#E4FC9D',
  middleBlueGreen: '#aaddd5',
  maximumBluePurple: '#95abfc',
  mauve: '#c6a7f8',
  pinkLavendar: '#f1b8e7'
};
